In [1]:
import os, sys
from glob import glob
import pandas as pd

In [3]:
bad_tiles_list = ['32726-31768-16.jpg', 
'32726-31767-16.jpg', 
'32724-31769-16.jpg', 
'32708-31765-16.jpg', 
'32707-31766-16.jpg', 
'16940-29811-16.jpg', 
'16939-29814-16.jpg', 
'16938-29814-16.jpg', 
'16937-29814-16.jpg', 
'16936-29814-16.jpg', 
'16935-29811-16.jpg', 
'16928-29809-16.jpg', 
'16934-29815-16.jpg', 
'16908-29804-16.jpg', 
'16907-29804-16.jpg', 
'16905-29803-16.jpg', 
'16903-29804-16.jpg', 
'16902-29804-16.jpg', 
'16902-29803-16.jpg', 
'16899-29804-16.jpg', 
'16833-29829-16.jpg', 
'16829-29830-16.jpg', 
'16817-29820-16.jpg', 
'16816-29827-16.jpg', 
'16816-29823-16.jpg', 
'16816-29820-16.jpg', 
'16815-29831-16.jpg', 
'16815-29830-16.jpg', 
'16815-29825-16.jpg', 
'16815-29824-16.jpg', 
'16768-29821-16.jpg', 
'16847-29830-16.jpg', 
'16847-29829-16.jpg', 
'16839-29824-16.jpg', 
'16839-29823-16.jpg', 
'16817-29828-16.jpg', 
'16811-29821-16.jpg', 
'16953-29799-16.jpg', 
'16952-29800-16.jpg', 
'16951-29797-16.jpg', 
'16946-29800-16.jpg', 
'16949-29799-16.jpg', 
'16942-29804-16.jpg', 
'16944-29801-16.jpg', 
'16720-29841-16.jpg', 
'16716-29831-16.jpg', 
'16714-29831-16.jpg', 
'16713-29829-16.jpg', 
'16708-29828-16.jpg', 
'16694-29828-16.jpg', 
'16713-29826-16.jpg', 
'16712-29827-16.jpg', 
'16725-29824-16.jpg', 
'16705-29847-16.jpg', 
'16704-29846-16.jpg', 
'16702-29849-16.jpg', 
'16903-29837-16.jpg', 
'16902-29838-16.jpg', 
'16902-29836-16.jpg', 
'16889-29839-16.jpg', 
'16888-29838-16.jpg', 
'16768-29703-16.jpg', 
'17294-29803-16.jpg', 
'17293-29803-16.jpg', 
'17292-29803-16.jpg', 
'17284-29804-16.jpg', 
'17283-29804-16.jpg', 
'17304-29800-16.jpg', 
'17302-29801-16.jpg', 
'17300-29802-16.jpg', 
'17300-29800-16.jpg', 
'17299-29802-16.jpg', 
'17132-29795-16.jpg', 
'17132-29794-16.jpg', 
'17127-29794-16.jpg', 
'17126-29792-16.jpg', 
'17125-29796-16.jpg', 
'17125-29795-16.jpg', 
'17119-29794-16.jpg', 
'17141-29808-16.jpg', 
'17141-29806-16.jpg', 
'17138-29801-16.jpg', 
'17137-29801-16.jpg', 
'17137-29800-16.jpg', 
'17134-29795-16.jpg', 
'17133-29797-16.jpg', 
'17068-29742-16.jpg', 
'17068-29743-16.jpg', 
'17068-29741-16.jpg', 
'17067-29742-16.jpg',
'17066-29741-16.jpg', 
'17066-29739-16.jpg',
'17065-29743-16.jpg',
'17065-29740-16.jpg', 
'17063-29744-16.jpg', 
'17063-29740-16.jpg', 
'17062-29742-16.jpg', 
'17059-29747-16.jpg', 
'17057-29747-16.jpg', 
'17069-29762-16.jpg', 
'17065-29757-16.jpg', 
'17074-29762-16.jpg', 
'17072-29764-16.jpg', 
'17071-29764-16.jpg', 
'17069-29756-16.jpg', 
'17068-29756-16.jpg', 
'17065-29755-16.jpg', 
'17064-29755-16.jpg', 
'17063-29756-16.jpg', 
'16757-29707-16.jpg', 
'16746-29703-16.jpg', 
'16744-29701-16.jpg', 
'16742-29702-16.jpg', 
'16770-29797-16.jpg', 
'16772-29797-16.jpg', 
'16773-29796-16.jpg', 
'16770-29792-16.jpg', 
'16770-29794-16.jpg', 
'16769-29791-16.jpg', 
'16743-29853-16.jpg', 
'16742-29853-16.jpg', 
'16736-29854-16.jpg', 
'16735-29845-16.jpg', 
'16733-29846-16.jpg', 
'16731-29850-16.jpg', 
'16733-29845-16.jpg', 
'16737-29854-16.jpg', 
'16736-29843-16.jpg', 
'16736-29842-16.jpg', 
'16735-29845-16.jpg', 
'16735-29839-16.jpg', 
'16734-29840-16.jpg', 
'16734-29833-16.jpg', 
'16733-29832-16.jpg', 
'16779-29802-16.jpg', 
'16775-29801-16.jpg', 
'16774-29801-16.jpg', 
'16773-29801-16.jpg', 
'16979-29813-16.jpg', 
'16978-29813-16.jpg', 
'16974-29815-16.jpg', 
'16974-29814-16.jpg', 
'16973-29816-16.jpg', 
'16973-29814-16.jpg', 
'16972-29816-16.jpg', 
'16970-29815-16.jpg', 
'16966-29818-16.jpg', 
'16965-29819-16.jpg', 
'16965-29816-16.jpg', 
'16964-29821-16.jpg', 
'16964-29820-16.jpg', 
'16963-29819-16.jpg', 
'17246-29821-16.jpg', 
'17244-29821-16.jpg', 
'17234-29818-16.jpg', 
'17100-29721-16.jpg', 
'17101-29718-16.jpg', 
'17098-29718-16.jpg', 
'17097-29718-16.jpg', 
'17095-29717-16.jpg', 
'17094-29716-16.jpg', 
'17105-29715-16.jpg', 
'17103-29714-16.jpg', 
'17103-29713-16.jpg', 
'17101-29714-16.jpg', 
'17100-29712-16.jpg', 
'17099-29713-16.jpg', 
'17096-29717-16.jpg', 
'17099-29712-16.jpg', 
'17097-29718-16.jpg', 
'17096-29718-16.jpg', 
'17095-29717-16.jpg', 
'17157-29727-16.jpg', 
'17157-29726-16.jpg', 
'17141-29729-16.jpg', 
'17142-29729-16.jpg', 
'17156-29727-16.jpg', 
'17155-29727-16.jpg', 
'17155-29726-16.jpg', 
'17154-29728-16.jpg', 
'17154-29726-16.jpg', 
'17154-29727-16.jpg', 
'17153-29727-16.jpg', 
'17151-29726-16.jpg', 
'17151-29725-16.jpg', 
'17150-29726-16.jpg', 
'17148-29725-16.jpg', 
'17147-29727-16.jpg', 
'17147-29725-16.jpg', 
'17146-29726-16.jpg', 
'17146-29725-16.jpg', 
'17140-29727-16.jpg', 
'17022-29743-16.jpg', 
'17017-29740-16.jpg', 
'17013-29743-16.jpg', 
'17012-29743-16.jpg', 
'17015-29742-16.jpg', 
'17009-29746-16.jpg', 
'17007-29747-16.jpg', 
'17005-29748-16.jpg', 
'17003-29748-16.jpg', 
'17027-29732-16.jpg', 
'17027-29731-16.jpg', 
'17026-29731-16.jpg', 
'17026-29728-16.jpg', 
'17022-29731-16.jpg', 
'17005-29748-16.jpg', 
'17003-29750-16.jpg', 
'17004-29749-16.jpg', 
'17002-29749-16.jpg', 
'17002-29751-16.jpg', 
'17028-29719-16.jpg', 
'17023-29717-16.jpg', 
'17020-29717-16.jpg', 
'17020-29713-16.jpg', 
'17027-29717-16.jpg', 
'17025-29722-16.jpg', 
'17025-29716-16.jpg', 
'17024-29719-16.jpg', 
'16744-29843-16.jpg', 
'16743-29845-16.jpg', 
'16743-29843-16.jpg', 
'16742-29844-16.jpg', 
'16741-29847-16.jpg', 
'16741-29845-16.jpg', 
'16740-29849-16.jpg', 
'16739-29850-16.jpg', 
'16930-29741-16.jpg', 
'16965-29751-16.jpg', 
'16965-29750-16.jpg', 
'16965-29749-16.jpg', 
'16964-29751-16.jpg', 
'16964-29749-16.jpg', 
'16963-29751-16.jpg', 
'16963-29750-16.jpg', 
'16963-29749-16.jpg', 
'16962-29751-16.jpg', 
'16961-29749-16.jpg', 
'16961-29748-16.jpg', 
'16960-29751-16.jpg', 
'16960-29749-16.jpg', 
'16960-29748-16.jpg', 
'16931-29741-16.jpg', 
'16931-29740-16.jpg', 
'16930-29741-16.jpg', 
'16930-29740-16.jpg', 
'16761-29685-16.jpg', 
'16759-29682-16.jpg', 
'16758-29683-16.jpg', 
'16758-29682-16.jpg', 
'16763-29687-16.jpg', 
'16762-29688-16.jpg', 
'16771-29692-16.jpg', 
'16769-29695-16.jpg', 
'16769-29693-16.jpg', 
'16768-29695-16.jpg', 
'16767-29694-16.jpg', 
'16767-29692-16.jpg', 
'16766-29693-16.jpg', 
'16765-29696-16.jpg', 
'16756-29693-16.jpg', 
'16756-29689-16.jpg', 
'16755-29693-16.jpg', 
'16761-29707-16.jpg', 
'16761-29708-16.jpg', 
'16766-29711-16.jpg', 
'16772-29702-16.jpg', 
'16765-29712-16.jpg', 
'16765-29713-16.jpg', 
'16769-29715-16.jpg', 
'16769-29717-16.jpg', 
'16770-29721-16.jpg', 
'16769-29720-16.jpg', 
'16766-29712-16.jpg']

In [ ]:
for file in bad_tiles_list:
    tiles = glob(f'data_v2/**/*{file}*',recursive=True)
    print(file, len(tiles))
    if len(tiles) > 1:
        print(tiles)

In [ ]:
for file in bad_tiles_list:
    tiles = glob(f'data_v2/**/*{file}*',recursive=True)
    print(file, len(tiles))

In [16]:
df = pd.read_csv('planet_colocation_events_04122021.csv')

In [17]:
df

,Scene_ID,Timestamp,Location (name),Gound truth coordinates (if available),Source study (if any),Approximate number of spotted aggregates,Description,Labeled (Yes/No),Notes for shapefile viz from merged geojsons,Tiles to Remove from tf dataset,Tiles with Missing Labels
0,20181031_095925_103b,10/31/2018,"Accra, Ghana","5.49209° N, 0.22454° W",NaN,38.0,NaN,Yes,NaN,"32726-31768-16.jpg, 32726-31767-16.jpg, 32724-...",NaN
1,20200804_100556_1005,8/4/2020,"Accra, Ghana","5.49209° N, 0.22454° W",NaN,20.0,NaN,Yes,NaN,NaN,NaN
2,20200501_100804_103c,05/01/2020,"Accra, Ghana","5.49209° N, 0.22454° W",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20200501_100803_103c,05/01/2020,"Accra, Ghana","5.49209° N, 0.22454° W",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20200501_100802_103c,05/01/2020,"Accra, Ghana","5.49209° N, 0.22454° W",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,1152.0,NaN,NaN,NaN,NaN,NaN

In [27]:
df_s = df[['Scene_ID','Tiles with Missing Labels']].copy()

In [33]:
filtered_df = df_s[df_s['Tiles with Missing Labels'].notnull()]

In [34]:
len(filtered_df)

14

In [35]:
filtered_df

                Scene_ID                          Tiles with Missing Labels
26  20181023_155746_0f34                                16725-29824-16.jpg
29  20170227_203601_0c46                                 16902-29836-16.jpg
37  20170326_153234_0e26             17069-29762-16.jpg, 17065-29757-16.jpg
38  20170326_154021_0e2f  16761-29707-16.jpg, 16752-29705-16.jpg, 16746-...
39  20170826_154047_100c                                 16773-29796-16.jpg
42  20170927_154611_0e14                                 16737-29854-16.jpg
48  20180224_153959_0f1b  17100-29721-16.jpg, 17101-29718-16.jpg, 17098-...
49  20180224_153958_0f1b  17099-29712-16.jpg, 17097-29718-16.jpg, 17096-...
50  20180224_162902_0f2b  17156-29727-16.jpg, 17155-29727-16.jpg, 17155-...
51  20180313_154300_1008                                 17003-29748-16.jpg
52  20180313_154259_1008                                 17022-29731-16.jpg
54  20180313_154258_1008  17027-29717-16.jpg, 17025-29722-16.jpg, 17025-...
56  20180919_155029_1044                                 16930-29740-16.jpg
60  20181124_155713_1049  16770-29721-16.jpg, 16769-29720-16.jpg, 16766-...

In [64]:
bad_tiles = []

In [66]:
for index, row in filtered_df.iterrows():
    row_t = str(row['Tiles with Missing Labels'])
    tiles = row_t.split(',')
    for t in tiles:
        tile_p = row['Scene_ID']+'/tiles/'+t
        tile_p = tile_p.replace(" ", "")
        bad_tiles.append(tile_p)

20181023_155746_0f34/tiles/16725-29824-16.jpg
20170227_203601_0c46/tiles/16902-29836-16.jpg
20170326_153234_0e26/tiles/17069-29762-16.jpg
20170326_153234_0e26/tiles/17065-29757-16.jpg
20170326_154021_0e2f/tiles/16761-29707-16.jpg
20170326_154021_0e2f/tiles/16752-29705-16.jpg
20170326_154021_0e2f/tiles/16746-29702-16.jpg
20170826_154047_100c/tiles/16773-29796-16.jpg
20170927_154611_0e14/tiles/16737-29854-16.jpg
20180224_153959_0f1b/tiles/17100-29721-16.jpg
20180224_153959_0f1b/tiles/17101-29718-16.jpg
20180224_153959_0f1b/tiles/17098-29718-16.jpg
20180224_153959_0f1b/tiles/17097-29718-16.jpg
20180224_153959_0f1b/tiles/17095-29717-16.jpg
20180224_153959_0f1b/tiles/17094-29716-16.jpg
20180224_153958_0f1b/tiles/17099-29712-16.jpg
20180224_153958_0f1b/tiles/17097-29718-16.jpg
20180224_153958_0f1b/tiles/17096-29718-16.jpg
20180224_153958_0f1b/tiles/17095-29717-16.jpg
20180224_162902_0f2b/tiles/17156-29727-16.jpg
20180224_162902_0f2b/tiles/17155-29727-16.jpg
20180224_162902_0f2b/tiles/17155-29726-16.jpg
20180224_162902_0f2b/tiles/17154-29728-16.jpg
20180224_162902_0f2b/tiles/17154-29726-16.jpg
20180224_162902_0f2b/tiles/17154-29727-16.jpg
20180224_162902_0f2b/tiles/17153-29727-16.jpg
20180224_162902_0f2b/tiles/17151-29726-16.jpg
20180224_162902_0f2b/tiles/17151-29725-16.jpg
20180224_162902_0f2b/tiles/17150-29726-16.jpg
20180224_162902_0f2b/tiles/17148-29725-16.jpg
20180224_162902_0f2b/tiles/17147-29727-16.jpg
20180224_162902_0f2b/tiles/17147-29725-16.jpg
20180224_162902_0f2b/tiles/17146-29726-16.jpg
20180224_162902_0f2b/tiles/17146-29725-16.jpg
20180224_162902_0f2b/tiles/17140-29727-16.jpg
20180313_154300_1008/tiles/17003-29748-16.jpg
20180313_154259_1008/tiles/17022-29731-16.jpg
20180313_154258_1008/tiles/17027-29717-16.jpg
20180313_154258_1008/tiles/17025-29722-16.jpg
20180313_154258_1008/tiles/17025-29716-16.jpg
20180313_154258_1008/tiles/17024-29719-16.jpg
20180919_155029_1044/tiles/16930-29740-16.jpg
20181124_155713_1049/tiles/16770-29721-16.jpg
20181124_155713_1049/tiles/16769-29720-16.jpg
20181124_155713_1049/tiles/16766-29712-16.jpg

In [67]:
len(bad_tiles)

45

In [68]:
os.chdir('data_v2')

In [69]:
!pwd

/Users/lillythomas/Documents/work/marine_litter_ML/geojsons/data_v3/data_v2

In [70]:
for tile in bad_tiles:
    os.remove(tile)

In [71]:
cd ..

/Users/lillythomas/Documents/work/marine_litter_ML/geojsons/data_v3

In [74]:
for file in bad_tiles:
    tiles = glob(f'data_v2/**/*{file}*',recursive=True)
    print(file, len(tiles))

20181023_155746_0f34/tiles/16725-29824-16.jpg 0
20170227_203601_0c46/tiles/16902-29836-16.jpg 0
20170326_153234_0e26/tiles/17069-29762-16.jpg 0
20170326_153234_0e26/tiles/17065-29757-16.jpg 0
20170326_154021_0e2f/tiles/16761-29707-16.jpg 0
20170326_154021_0e2f/tiles/16752-29705-16.jpg 0
20170326_154021_0e2f/tiles/16746-29702-16.jpg 0
20170826_154047_100c/tiles/16773-29796-16.jpg 0
20170927_154611_0e14/tiles/16737-29854-16.jpg 0
20180224_153959_0f1b/tiles/17100-29721-16.jpg 0
20180224_153959_0f1b/tiles/17101-29718-16.jpg 0
20180224_153959_0f1b/tiles/17098-29718-16.jpg 0
20180224_153959_0f1b/tiles/17097-29718-16.jpg 0
20180224_153959_0f1b/tiles/17095-29717-16.jpg 0
20180224_153959_0f1b/tiles/17094-29716-16.jpg 0
20180224_153958_0f1b/tiles/17099-29712-16.jpg 0
20180224_153958_0f1b/tiles/17097-29718-16.jpg 0
20180224_153958_0f1b/tiles/17096-29718-16.jpg 0
20180224_153958_0f1b/tiles/17095-29717-16.jpg 0
20180224_162902_0f2b/tiles/17156-29727-16.jpg 0
20180224_162902_0f2b/tiles/17155-29727-16.jpg 0
20180224_162902_0f2b/tiles/17155-29726-16.jpg 0
20180224_162902_0f2b/tiles/17154-29728-16.jpg 0
20180224_162902_0f2b/tiles/17154-29726-16.jpg 0
20180224_162902_0f2b/tiles/17154-29727-16.jpg 0
20180224_162902_0f2b/tiles/17153-29727-16.jpg 0
20180224_162902_0f2b/tiles/17151-29726-16.jpg 0
20180224_162902_0f2b/tiles/17151-29725-16.jpg 0
20180224_162902_0f2b/tiles/17150-29726-16.jpg 0
20180224_162902_0f2b/tiles/17148-29725-16.jpg 0
20180224_162902_0f2b/tiles/17147-29727-16.jpg 0
20180224_162902_0f2b/tiles/17147-29725-16.jpg 0
20180224_162902_0f2b/tiles/17146-29726-16.jpg 0
20180224_162902_0f2b/tiles/17146-29725-16.jpg 0
20180224_162902_0f2b/tiles/17140-29727-16.jpg 0
20180313_154300_1008/tiles/17003-29748-16.jpg 0
20180313_154259_1008/tiles/17022-29731-16.jpg 0
20180313_154258_1008/tiles/17027-29717-16.jpg 0
20180313_154258_1008/tiles/17025-29722-16.jpg 0
20180313_154258_1008/tiles/17025-29716-16.jpg 0
20180313_154258_1008/tiles/17024-29719-16.jpg 0
20180919_155029_1044/tiles/16930-29740-16.jpg 0
20181124_155713_1049/tiles/16770-29721-16.jpg 0
20181124_155713_1049/tiles/16769-29720-16.jpg 0
20181124_155713_1049/tiles/16766-29712-16.jpg 0

In [75]:
for file in bad_tiles:
    tiles = glob(f'data_v2_backup/**/*{file}*',recursive=True)
    print(file, len(tiles))

20181023_155746_0f34/tiles/16725-29824-16.jpg 1
20170227_203601_0c46/tiles/16902-29836-16.jpg 1
20170326_153234_0e26/tiles/17069-29762-16.jpg 1
20170326_153234_0e26/tiles/17065-29757-16.jpg 1
20170326_154021_0e2f/tiles/16761-29707-16.jpg 1
20170326_154021_0e2f/tiles/16752-29705-16.jpg 1
20170326_154021_0e2f/tiles/16746-29702-16.jpg 1
20170826_154047_100c/tiles/16773-29796-16.jpg 1
20170927_154611_0e14/tiles/16737-29854-16.jpg 1
20180224_153959_0f1b/tiles/17100-29721-16.jpg 1
20180224_153959_0f1b/tiles/17101-29718-16.jpg 1
20180224_153959_0f1b/tiles/17098-29718-16.jpg 1
20180224_153959_0f1b/tiles/17097-29718-16.jpg 1
20180224_153959_0f1b/tiles/17095-29717-16.jpg 1
20180224_153959_0f1b/tiles/17094-29716-16.jpg 1
20180224_153958_0f1b/tiles/17099-29712-16.jpg 1
20180224_153958_0f1b/tiles/17097-29718-16.jpg 1
20180224_153958_0f1b/tiles/17096-29718-16.jpg 1
20180224_153958_0f1b/tiles/17095-29717-16.jpg 1
20180224_162902_0f2b/tiles/17156-29727-16.jpg 1
20180224_162902_0f2b/tiles/17155-29727-16.jpg 1
20180224_162902_0f2b/tiles/17155-29726-16.jpg 1
20180224_162902_0f2b/tiles/17154-29728-16.jpg 1
20180224_162902_0f2b/tiles/17154-29726-16.jpg 1
20180224_162902_0f2b/tiles/17154-29727-16.jpg 1
20180224_162902_0f2b/tiles/17153-29727-16.jpg 1
20180224_162902_0f2b/tiles/17151-29726-16.jpg 1
20180224_162902_0f2b/tiles/17151-29725-16.jpg 1
20180224_162902_0f2b/tiles/17150-29726-16.jpg 1
20180224_162902_0f2b/tiles/17148-29725-16.jpg 1
20180224_162902_0f2b/tiles/17147-29727-16.jpg 1
20180224_162902_0f2b/tiles/17147-29725-16.jpg 1
20180224_162902_0f2b/tiles/17146-29726-16.jpg 1
20180224_162902_0f2b/tiles/17146-29725-16.jpg 1
20180224_162902_0f2b/tiles/17140-29727-16.jpg 1
20180313_154300_1008/tiles/17003-29748-16.jpg 1
20180313_154259_1008/tiles/17022-29731-16.jpg 1
20180313_154258_1008/tiles/17027-29717-16.jpg 1
20180313_154258_1008/tiles/17025-29722-16.jpg 1
20180313_154258_1008/tiles/17025-29716-16.jpg 1
20180313_154258_1008/tiles/17024-29719-16.jpg 1
20180919_155029_1044/tiles/16930-29740-16.jpg 1
20181124_155713_1049/tiles/16770-29721-16.jpg 1
20181124_155713_1049/tiles/16769-29720-16.jpg 1
20181124_155713_1049/tiles/16766-29712-16.jpg 1